spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
    discovery:
      enabled: true
server:
  port: 1124
#    gateway:
#        routes:
#          - id: r1
#            uri: http://localhost:8081
#            predicates:
#              - Path= /customers/**
#          - id: r2
#            uri:
#              http://localhost:8082
#            predicates:
#              - Path= /products/**